#Geyser-Updater
#Made by Jens & YHDiamond

# NOTICE! Read the information on our GitHub before using this plugin!
# https://github.com/YHDiamond/GeyserUpdater


EnableAutoUpdateGeyser: false

EnableAutoRestart: false

RestartMessage: '&2The server will restart in 10 Seconds!'

EnableAutoScript: false
